-- AlterEnum
-- 修正申請のADD_BREAK/ADD_INTERRUPTをSTART/END区別できるよう新値を追加。
-- 既存のADD_BREAK/ADD_INTERRUPTは非推奨扱いで残す（既存データ保持）。
ALTER TYPE "ModReqType" ADD VALUE 'ADD_BREAK_START';
ALTER TYPE "ModReqType" ADD VALUE 'ADD_BREAK_END';
ALTER TYPE "ModReqType" ADD VALUE 'ADD_INTERRUPT_START';
ALTER TYPE "ModReqType" ADD VALUE 'ADD_INTERRUPT_END';
