/* eslint-disable @typescript-eslint/no-explicit-any --
   検証スクリプトは API レスポンスを素の JSON として扱う（本体の型に追随させない）。 */
// T-147 改修（TO/CC 1通送信）の staging / 本番 動作確認スクリプト。
//
// 実行:
//   npx tsx scripts/verify_t147_tocc.ts staging
//   npx tsx scripts/verify_t147_tocc.ts production --keep   （--keep = 無効化テストをせずレコードを残す）
//
// 認証は前回フェーズと同じ Cookie 方式（bs_session = User.id・src/lib/auth.ts）。
// パスワード入力は不要なのでブラウザを使わない。
//
// ★安全設計
//   - 送信先は TEST_ADDRESS（masayuki_oono@bizstudio.co.jp）のみ。他アドレスが混ざったら即異常終了。
//   - staging と本番は同一 Postgres。ここで作るデータは実データになる。
//   - 既存レコードの書き換え・削除は一切しない（読み取りと、自分で作ったレコードの無効化のみ）。

const ACTOR_USER_ID = "cml9jturt00037k4ftqsi6yvz"; // 大野 将幸（admin）
const TEST_ADDRESS = "masayuki_oono@bizstudio.co.jp"; // ★これ以外へは絶対に送らない

const HOSTS = {
  staging: "https://bizstudio-portal-staging-production.up.railway.app",
  production: "https://bizstudio-portal-production.up.railway.app",
} as const;

const target = (process.argv[2] ?? "staging") as keyof typeof HOSTS;
const KEEP = process.argv.includes("--keep");
const BASE = HOSTS[target];
if (!BASE) {
  console.error(`unknown target: ${target}（staging | production）`);
  process.exit(1);
}

const UA = "bizstudio-portal-verify/1.0";

let pass = 0;
let fail = 0;
const results: string[] = [];

function check(id: string, ok: boolean, detail: string) {
  if (ok) pass++;
  else fail++;
  const line = `[${ok ? "OK" : "NG"}] ${id}  ${detail}`;
  results.push(line);
  console.log(line);
}

async function api(path: string, init: RequestInit = {}) {
  const res = await fetch(`${BASE}${path}`, {
    ...init,
    redirect: "manual",
    headers: {
      "Content-Type": "application/json",
      "User-Agent": UA,
      Cookie: `bs_session=${ACTOR_USER_ID}`,
      ...(init.headers ?? {}),
    },
  });
  const text = await res.text();
  let json: any = null;
  try {
    json = JSON.parse(text);
  } catch {
    /* HTML 等 */
  }
  return { status: res.status, json, text, headers: res.headers };
}

/** 認証なし（社外の受信者と同じ立場）でのアクセス。 */
async function pub(path: string, init: RequestInit = {}) {
  const res = await fetch(`${BASE}${path}`, {
    ...init,
    redirect: "manual",
    headers: { "User-Agent": UA, ...(init.headers ?? {}) },
  });
  const text = await res.text();
  let json: any = null;
  try {
    json = JSON.parse(text);
  } catch {
    /* HTML 等 */
  }
  return { status: res.status, json, text, headers: res.headers };
}

async function main() {
  console.log(`\n=== T-147 TO/CC 1通送信 動作確認 (${target}) ===`);
  console.log(`base=${BASE}\n`);

  // ---------------------------------------------------------------- 送信準備
  const fileName = `t147-tocc-test-${target}.txt`;
  const content = Buffer.from(
    `T-147 TO/CC single-mail verification (${target})\ngenerated by scripts/verify_t147_tocc.ts\n`,
    "utf8"
  );

  const up = await api("/api/transfers/upload-url", {
    method: "POST",
    body: JSON.stringify({ fileName, fileSize: content.length }),
  });
  if (up.status !== 200 || !up.json?.signedUrl) {
    console.error("upload-url failed:", up.status, up.text.slice(0, 300));
    process.exit(1);
  }

  const putRes = await fetch(up.json.signedUrl, {
    method: "PUT",
    headers: { "Content-Type": "text/plain", "User-Agent": UA },
    body: content,
  });
  if (!putRes.ok) {
    console.error("supabase upload failed:", putRes.status);
    process.exit(1);
  }

  // ---------------------------------------------------------------- V-6 先に実施（宛先空欄）
  const emptyTo = await api("/api/transfers", {
    method: "POST",
    body: JSON.stringify({
      recipientEmails: [],
      ccEmails: [TEST_ADDRESS],
      files: [{ fileName, fileSize: content.length, storagePath: up.json.storagePath }],
    }),
  });
  check(
    "V-6 宛先空欄はエラー",
    emptyTo.status === 400 && typeof emptyTo.json?.error === "string",
    `status=${emptyTo.status} error=${emptyTo.json?.error ?? "-"}`
  );

  // ---------------------------------------------------------------- V-1 送信（TO 1件 / CC 1件）
  const listBefore = await api("/api/transfers");
  const countBefore = (listBefore.json?.transfers ?? []).length;

  const recipients = [TEST_ADDRESS];
  const ccs = [TEST_ADDRESS];
  // 安全ガード: テストアドレス以外が混ざっていたら送らない
  for (const a of [...recipients, ...ccs]) {
    if (a !== TEST_ADDRESS) {
      console.error(`SAFETY ABORT: 想定外の宛先 ${a}`);
      process.exit(1);
    }
  }

  const send = await api("/api/transfers", {
    method: "POST",
    body: JSON.stringify({
      recipientEmails: recipients,
      ccEmails: ccs,
      subject: `T-147 TO/CC 検証 (${target})`,
      message: "T-147 の TO/CC 1通送信の動作確認です。",
      signature: "──\n株式会社ビズスタジオ 大野 将幸\nmasayuki_oono@bizstudio.co.jp",
      expiresDays: 1,
      passwordInEmail: true,
      files: [{ fileName, fileSize: content.length, storagePath: up.json.storagePath }],
    }),
  });

  if (send.status !== 201) {
    console.error("send failed:", send.status, send.text.slice(0, 500));
    process.exit(1);
  }

  const listAfter = await api("/api/transfers");
  const rowsAfter = listAfter.json?.transfers ?? [];
  const createdRows = rowsAfter.filter((r: any) => r.id === send.json.id);
  const newRowCount = rowsAfter.length - countBefore;

  check(
    "V-1 送信は1レコード＝メール1通",
    newRowCount === 1 && createdRows.length === 1,
    `新規レコード数=${newRowCount}（期待 1） transferId=${send.json.id}`
  );
  check(
    "V-1 TO と CC の両方にテストアドレス",
    JSON.stringify(send.json.recipientEmails) === JSON.stringify([TEST_ADDRESS]) &&
      JSON.stringify(send.json.ccEmails) === JSON.stringify([TEST_ADDRESS]),
    `to=${JSON.stringify(send.json.recipientEmails)} cc=${JSON.stringify(send.json.ccEmails)}`
  );

  // ---------------------------------------------------------------- V-2 URL/パスワードが1組
  check(
    "V-2 URL・パスワードは1組",
    typeof send.json.url === "string" &&
      typeof send.json.password === "string" &&
      send.json.transfers === undefined, // 旧形式（宛先ごとの配列）が残っていないこと
    `url=${String(send.json.url).replace(/\/transfer\/.*$/, "/transfer/***")} passwordLen=${String(send.json.password).length} 旧transfers配列=${send.json.transfers === undefined ? "なし" : "あり"}`
  );

  const token = String(send.json.url).split("/transfer/")[1];
  const password = String(send.json.password);

  // ---------------------------------------------------------------- V-3 URL+パスワードでDL
  const statusBefore = await pub(`/api/transfer/${token}/status`);
  const verify = await pub(`/api/transfer/${token}/verify`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ password }),
  });
  const setCookie = verify.headers.get("set-cookie") ?? "";
  const accessCookie = setCookie.split(";")[0];
  const fileId = verify.json?.files?.[0]?.id;

  let dlStatus = 0;
  let dlHasSignedUrl = false;
  if (fileId && accessCookie) {
    const dl = await pub(`/api/transfer/${token}/download/${fileId}`, {
      headers: { Cookie: accessCookie },
    });
    dlStatus = dl.status;
    dlHasSignedUrl = (dl.headers.get("location") ?? "").includes("supabase");
  }
  check(
    "V-3 URLとパスワードでダウンロードできる",
    statusBefore.json?.available === true &&
      verify.status === 200 &&
      (dlStatus === 302 || dlStatus === 307) &&
      dlHasSignedUrl,
    `status.available=${statusBefore.json?.available} verify=${verify.status} download=${dlStatus} 署名URLへリダイレクト=${dlHasSignedUrl}`
  );

  // ---------------------------------------------------------------- V-4 一覧の表示データ
  const row = createdRows[0];
  check(
    "V-4 一覧は1行で宛先とCCの両方を持つ",
    row?.recipientEmail === TEST_ADDRESS && row?.ccEmails === TEST_ADDRESS,
    `recipientEmail=${row?.recipientEmail} ccEmails=${row?.ccEmails}`
  );

  const detail = await api(`/api/transfers/${send.json.id}`);
  check(
    "V-4 詳細APIも宛先とCCを返す",
    detail.status === 200 &&
      detail.json?.recipientEmail === TEST_ADDRESS &&
      detail.json?.ccEmails === TEST_ADDRESS,
    `status=${detail.status} to=${detail.json?.recipientEmail} cc=${detail.json?.ccEmails} downloads=${detail.json?.downloads?.length ?? "-"}`
  );

  // ---------------------------------------------------------------- V-8 過去の batch 形式レコード
  const legacy = rowsAfter.filter((r: any) => r.batchId !== null);
  const legacyGroups = new Set(legacy.map((r: any) => r.batchId));
  const legacyOk = legacy.every(
    (r: any) =>
      typeof r.recipientEmail === "string" &&
      r.recipientEmail.length > 0 &&
      r.ccEmails === null &&
      typeof r.status === "string" &&
      Array.isArray(r.files)
  );
  check(
    "V-8 過去の batch 形式レコードが一覧で崩れない",
    legacy.length > 0 && legacyOk,
    `batch形式レコード=${legacy.length}件（batch数=${legacyGroups.size}）・全件 recipientEmail あり / ccEmails=null / files配列あり=${legacyOk}`
  );

  // ---------------------------------------------------------------- V-9 /share/[token]
  const shareBad = await pub("/share/definitely-not-a-real-token-t147");
  const shareApi = await pub("/api/share/definitely-not-a-real-token-t147");
  check(
    "V-9 /share/[token] が従来どおり応答する",
    (shareBad.status === 200 || shareBad.status === 404) && shareApi.status !== 500,
    `/share/<不正token> status=${shareBad.status} /api/share/<不正token> status=${shareApi.status}（500 でなければ既存動作維持）`
  );

  // ---------------------------------------------------------------- V-5 無効化
  if (KEEP) {
    check(
      "V-5 無効化（--keep のためスキップ）",
      true,
      "本番はテストレコードを残す指定のため無効化しない"
    );
  } else {
    const revoke = await api(`/api/transfers/${send.json.id}/revoke`, { method: "POST" });
    const statusAfter = await pub(`/api/transfer/${token}/status`);
    const verifyAfter = await pub(`/api/transfer/${token}/verify`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ password }),
    });
    let dlAfter = 0;
    if (fileId && accessCookie) {
      const dl = await pub(`/api/transfer/${token}/download/${fileId}`, {
        headers: { Cookie: accessCookie },
      });
      dlAfter = dl.status;
    }
    check(
      "V-5 無効化するとURLが開けなくなる",
      revoke.status === 200 &&
        statusAfter.json?.available === false &&
        verifyAfter.status === 404 &&
        dlAfter === 404,
      `revoke=${revoke.status} status.available=${statusAfter.json?.available} verify=${verifyAfter.status} download=${dlAfter}`
    );
  }

  // ---------------------------------------------------------------- サマリ
  console.log(`\n--- 結果: ${pass} OK / ${fail} NG ---`);
  console.log(`transferId=${send.json.id}`);
  console.log(`※ V-7（ドメイン混在警告）はクライアント側描画のため別途確認する`);
  if (fail > 0) process.exit(1);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
